# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 09:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projectName', models.CharField(max_length=20, unique=True)),
                ('createDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeployPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('compose', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Swarm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('ip', models.CharField(db_index=True, max_length=15)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SwarmCluster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
            ],
        ),
        migrations.AddField(
            model_name='swarm',
            name='swarmCluster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deploy.SwarmCluster'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='deployPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deploy.DeployPlan'),
        ),
        migrations.AddField(
            model_name='deployment',
            name='swarm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deploy.Swarm'),
        ),
        migrations.AlterUniqueTogether(
            name='swarm',
            unique_together=set([('name', 'ip')]),
        ),
        migrations.AlterUniqueTogether(
            name='deployment',
            unique_together=set([('projectName', 'deployPlan', 'swarm')]),
        ),
    ]
