# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cluster',
            name='project',
            field=models.CharField(default='test', max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cluster',
            name='dns',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='cluster',
            unique_together=set([('dns', 'project')]),
        ),
        migrations.AlterUniqueTogether(
            name='deploysequence',
            unique_together=set([('deployPlan', 'sequence')]),
        ),
    ]
