# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deploy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='renderCompose',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
