# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-11 10:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deploy', '0002_deployment_rendercompose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='renderCompose',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='deployment',
            name='swarm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deploy.SwarmCluster'),
        ),
    ]
