# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-13 08:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deploy', '0003_auto_20161211_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serviceID', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='deployment',
            name='projectName',
            field=models.CharField(max_length=120, unique=True),
        ),
        migrations.AddField(
            model_name='service',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deploy.Deployment'),
        ),
    ]
