# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-19 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deploy', '0004_auto_20161213_0805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deployment',
            name='projectName',
            field=models.CharField(max_length=120),
        ),
    ]
