# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DataBaseConfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('containerID', models.CharField(max_length=15)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberOfInstance', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('R', 'Running'), ('S', 'Stopped'), ('W', 'Waiting')], max_length=10)),
                ('dataBase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBaseConfig.DataBase')),
            ],
        ),
        migrations.CreateModel(
            name='DockerServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=120)),
                ('ip', models.CharField(db_index=True, max_length=15)),
                ('port', models.IntegerField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='dockerserver',
            unique_together=set([('name', 'ip')]),
        ),
        migrations.AddField(
            model_name='deployment',
            name='dockerServer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deploy.DockerServer'),
        ),
        migrations.AddField(
            model_name='container',
            name='deployment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Deploy.Deployment'),
        ),
    ]
