# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configtype',
            name='explain',
            field=models.TextField(blank=True),
        ),
    ]
