# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataBase', '0002_auto_20161123_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instancetype',
            name='explain',
            field=models.TextField(blank=True),
        ),
    ]
