# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('DockerConfig', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationName', models.CharField(max_length=120)),
                ('dbName', models.CharField(max_length=120)),
                ('hostVolumePath', models.TextField()),
                ('containerVolumePath', models.TextField()),
                ('deploymentConfig', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DockerConfig.DeploymentConfig')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='database',
            unique_together=set([('applicationName', 'dbName')]),
        ),
    ]
