# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-23 13:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('explain', models.TextField()),
                ('ansiblePlaybook', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='InstanceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('imageName', models.CharField(max_length=120)),
                ('explain', models.TextField()),
                ('ansiblePlaybook', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='configtype',
            name='instanceType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DataBase.InstanceType'),
        ),
    ]
