# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataBaseImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('explain', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeploymentConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('config', models.TextField(blank=True)),
                ('dataBaseImage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DockerConfig.DataBaseImage')),
            ],
        ),
        migrations.CreateModel(
            name='EnvironmentVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variableName', models.CharField(max_length=120)),
                ('variableValue', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='environmentvariable',
            unique_together=set([('variableName', 'variableValue')]),
        ),
        migrations.AddField(
            model_name='databaseimage',
            name='environmentVariable',
            field=models.ManyToManyField(to='DockerConfig.EnvironmentVariable'),
        ),
    ]
